server:
  port: 8080

spring:
  application:
    name: system-insight
  datasource:
    url: jdbc:mysql://localhost:3306/ranking
    username: root
    password: 1234
    hikari:
      maximumPoolSize: 150    # 최대 DB 커넥션 수
      minimumIdle: 10        # 최소 유휴 커넥션 수
      connectionTimeout: 5000  # 커넥션 타임아웃 (ms)

  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2000ms
      lettuce: # lettuce 클라이언트 사용시 커넥션풀 설정
        pool:
          max-active: 200 #동시 할당 최대 커넥션
          max-idle: 100 # 유지될 수 있는 최대 유휴 커넥션 수
          min-idle: 20 # 유지되어야하는 최대 유휴 커넥션 수
          max-wait: 2000ms # 커넥션 요청시 대기할 최대 시간 (-1ms는 무한 대기)
